delivery/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('check-in',CheckIn),
    path('current-location',CurrentLocation),
    path('deliverer-profile/',DelivererProfileView),
    path('deliverer-profile/delivery-list',DeliveryListView),
    path('deliverer-profile/delivery-list/<int:page_id>/get-data',GetDelivererListData),
    path('deliverer-profile/deliveries/<int:page_id>',DeliveryView),
    path('current-delivery',CurrentDeliveryView),
    path('current-delivery/get-data',GetCurrentDeliveryData)
]

foodapp/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from products.views import ProductListView
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('',include('profiles.urls')),
    path('',include('stores.urls')),
    path('',include('orders.urls')),
    path('',include('delivery.urls')),
    path('',include('moderating.urls')),
    path('',Home),
    path('login',LoginPage),
    path('register',RegistrationPage),
    path('routing-test',RouteTest),
    path('logout',LogoutPage),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('current-order/',CurrentOrderView),
    path('current-order/get-data',GetCurrentOrderData),
    path('current-order/deliverer-location',DelivererCurrentLocation)
]

stores/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('store-list/<int:page_id>',StoreListView),
    path('store/<slug:slug>',StoreDetailView),
    path('current-store/',StoreView),
    path('current-store/get-statistic',GetStoreData),
    path('current-store/product-list/<int:page_id>',StoreProductView),
    path('current-store/order-product/<int:page_id>',OrderProductView),
    path('current-store/latest-order-product',GetLatestOrderProduct),
    path('current-store/order-product/<int:page_id>/get-data',GetOrderProductsData),
    path('current-store/product/<slug:slug>',ProductUpdateView),
    path('current-store/product/<slug:slug>/<int:page_id>/get-reviews',GetProductReviews),
    path('current-store/product/<slug:slug>/get-statistic',GetProductStatistic),
    path('current-store/create-product',ProductCreateView)
]

profiles/models.py
from django.db import models,transaction
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from locations.models import Location
from orders.models import Order,Order_Product
from products.models import Product_Review
from django.contrib.auth.models import Group
from phonenumber_field.validators import validate_international_phonenumber
from django.core.validators import validate_email
from foodapp.settings import MAX_MONTHLY_CANCELLATIONS
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate,login,logout
from axes.utils import reset

import datetime
# Create your models here.

class User_Status(models.Model):
	code = models.CharField(max_length=20)
	class Meta:
		db_table = "User_Status"
		verbose_name = "User_Status"

	def __str__(self):
		return self.code


class Gender(models.Model):
	code = models.CharField(max_length=20)
	class Meta:
		db_table = "Gender"
		verbose_name = "Gender"

	def __str__(self):
		return self.code

class Profile(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
	first_name = models.CharField(max_length = 256,blank = True)
	last_name = models.CharField(max_length = 256,blank = True)
	gender = models.ForeignKey(Gender,on_delete=models.SET_NULL,blank=True,null=True)
	birthdate = models.DateField(blank=True,null=True)
	citizen_identity_card = models.DecimalField(max_digits=12,decimal_places=0,null=True,blank=True)
	email = models.EmailField(unique=True)
	phone_number = PhoneNumberField(region = "VI",unique=True)
	avatar = models.ImageField(default='avatars/avatar.png', upload_to='avatars/')
	location = models.ForeignKey(Location,on_delete=models.SET_NULL,null=True)
	status = models.ForeignKey(User_Status,on_delete=models.DO_NOTHING,blank=True,null=True)
	current_order = models.ForeignKey(Order,on_delete=models.SET_NULL,blank=True,null=True)
	moderated = models.DateTimeField(blank=True, null=True)
	updated = models.DateTimeField(auto_now=True)
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		db_table = "Profiles"
		verbose_name = "Profile"

	def __str__(self):
		return f"{self.user.username}"

	@property
	def remain_cancellations(self):
		current_year = datetime.datetime.now().year
		current_month = datetime.datetime.now().month
		return max(0, MAX_MONTHLY_CANCELLATIONS - len(
			self.user.customer_orders.filter(created__year=current_year, created__month=current_month,
							   order_status__code="cancelled")))
	def purchased_product(self,product):
		return len(Order_Product.objects.filter(order__customer=self.user,
												product=product,status__code="received")) > 0
	def get_review(self,product):
		try:
			with transaction.atomic():
				return Product_Review.objects.get(author=self.user, product=product)
		except:
			return None


	def birthdate_update(self,date):
		str_date = date.split("-")
		int_date = [int(i) for i in str_date]
		new_birthdate = datetime.date(*int_date)
		if new_birthdate > datetime.datetime.now().date():
			raise ValidationError("Ngày sinh không thể là ngày sau ngày hôm nay")
		self.birthdate = new_birthdate

	def update_profile(self,request):
		self.first_name = request.POST.get("first_name")
		self.last_name = request.POST.get("last_name")
		self.gender_id = request.POST.get("gender")

		validate_email(request.POST.get("email"))
		validate_international_phonenumber(request.POST.get("phone_number"))

		self.birthdate_update(request.POST.get("birthdate"))
		self.phone_number = request.POST.get("phone_number")
		self.email = request.POST.get("email")
		self.citizen_identity_card = request.POST.get("citizen_identity_card")

		self.save()

	def update_location(self,request):
		if self.location == None:
			self.location = Location.objects.create()

		self.location.lat = request.POST.get("lat")
		self.location.lng = request.POST.get("lng")
		self.location.address = request.POST.get("address")
		self.location.country = request.POST.get("country")
		self.location.region = request.POST.get("region")
		self.location.subregion_1 = request.POST.get("subregion_1")
		self.location.subregion_2 = request.POST.get("subregion_2")
		self.location.save()

	def change_password(self,request):
		username = self.user.username
		if not authenticate(request, username=username, password=request.POST.get("old_password")):
			raise ValidationError("Bạn đã nhập sai mật khẩu cũ.")
		if request.POST.get("new_password_1") != request.POST.get("new_password_2"):
			raise ValidationError("Bạn đã nhập sai mật khẩu mới.")
		self.user.set_password(request.POST.get("new_password_1"))
		self.user.save()

		user = authenticate(request, username=username, password=request.POST.get("new_password_1"))
		if user is not None:
			login(request, user)


	@property
	def is_customer(self):
		return Group.objects.get(name="Customers") in self.user.groups.all()

	@property
	def is_store_owner(self):
		return Group.objects.get(name="StoreOwners") in self.user.groups.all()

	@property
	def is_deliverer(self):
		return Group.objects.get(name="Deliverers") in self.user.groups.all()

	@property
	def is_moderator(self):
		return Group.objects.get(name="Moderators") in self.user.groups.all()

stores/models.py
from django.db import models
from locations.models import  Location
from django.contrib.auth.models import User
import datetime
from django.core.exceptions import ValidationError,ObjectDoesNotExist
from locations.utils import distance
from djmoney.money import Money
from foodapp.utils import image_upload


WEEKDAYS = [
  (0, "Monday"),
  (1, "Tuesday"),
  (2, "Wednesday"),
  (3, "Thursday"),
  (4, "Friday"),
  (5, "Saturday"),
  (6, "Sunday"),
]

# Create your models here.

class Store_Status(models.Model):
	code = models.CharField(max_length=20)

	class Meta:
		db_table = "Store_Status"
		verbose_name = "Store_Status"

	def __str__(self):
		return self.code


class Store(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE,related_name="store")
	name = models.CharField(max_length = 256,blank = False)
	business_code = models.CharField(max_length =10,blank=True,null=True)
	tax_identification = models.CharField(max_length =13,blank=True,null=True)
	location = models.ForeignKey(Location,on_delete=models.SET_NULL,null=True)
	description = models.TextField(max_length = 512,blank=True)
	avatar = models.ImageField(default='stores/store.png', upload_to='stores/')
	status = models.ForeignKey(Store_Status,on_delete=models.SET_NULL,blank=True,null=True)
	slug = models.SlugField(max_length=255,null=True)
	moderated = models.DateTimeField(blank=True,null=True)
	updated = models.DateTimeField(auto_now=True)
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		db_table = "Store"
		verbose_name = "Store"

	def __str__(self):
		return f"{self.name} - {self.user.profile.first_name} {self.user.profile.last_name}"

	@property
	def is_open(self):
		today = datetime.datetime.now()
		try:
			now_weekday = today.weekday()
			now_hour = today.time()
			today_opening_hour = self.opening_hours.get(weekday=now_weekday)
			return self.status.code == "active" and now_hour >= today_opening_hour.from_hour and now_hour <= today_opening_hour.to_hour
		except:
			return False

	def distance_to(self,location):
		return distance(self.location,location)

	def update_store(self,request):
		self.name = request.POST.get("name")
		self.business_code = request.POST.get("business_code")
		self.tax_identification = request.POST.get("tax_identification")
		self.description = request.POST.get("description")

		self.save()

	def update_location(self,request):
		if self.location == None:
			self.location = Location.objects.create()

		self.location.lat = request.POST.get("lat")
		self.location.lng = request.POST.get("lng")
		self.location.address = request.POST.get("address")
		self.location.country = request.POST.get("country")
		self.location.region = request.POST.get("region")
		self.location.subregion_1 = request.POST.get("subregion_1")
		self.location.subregion_2 = request.POST.get("subregion_2")
		self.location.save()

	def create_product(self,request,status,category):
		name = request.POST.get("name")
		price = float(request.POST.get("price"))
		if price <= 0:
			raise ValidationError("Giá của món không thể nhỏ hơn 0")
		description = request.POST.get("description")
		image = request.FILES.get("image")
		slug = f"{name.replace(' ','-')}-{self.slug}"

		product = self.products.create(name = name,price = Money(price,'VND'),description = description,
									   category = category,store=self,status=status,slug = slug)

		if image != None:
			image_upload('products',product,image)

		product.save()



class Store_Opening_Hours(models.Model):
	store = models.ForeignKey(Store,on_delete=models.CASCADE,related_name="opening_hours")
	weekday = models.IntegerField(choices=WEEKDAYS,blank=True,null=True)
	from_hour = models.TimeField(blank=True,null=True)
	to_hour = models.TimeField(blank=True,null=True)
	class Meta:
		unique_together = ['store','weekday']

	def __str__(self):
		return f"{self.store.name} {self.get_weekday_display()} {self.from_hour} {self.to_hour}"

	def update(self,str_from_hour,str_to_hour):
		if str_from_hour == "" and str_to_hour == "":
			self.from_hour = None
			self.to_hour = None
		else:
			try:
				from_hour = datetime.datetime.strptime(str_from_hour,"%H:%M").time()
				to_hour = datetime.datetime.strptime(str_to_hour,"%H:%M").time()
				assert from_hour < to_hour
				self.from_hour = from_hour
				self.to_hour = to_hour
				self.save()
			except Exception as e:
				raise ValidationError(f"Thời gian nhập của {self.get_weekday_display()} vào không hợp lệ")


class Store_Image(models.Model):
	store = models.ForeignKey(Store, on_delete=models.CASCADE, related_name="images")
	image = models.ImageField(default='stores/images/store_image.png', upload_to='stores/images')

profiles/forms.py
from django.forms import ModelForm
from .models import Profile

class ProfileAvatarForm(ModelForm):
    class Meta:
        model = Profile
        fields = ["avatar"]

templates/Site/DelivererOrderList.html
{% extends 'Site/index.html' %}
{% block content %}
    <div class = "container-fluid">
        {% if user.is_authenticated %}
            <ul class="nav nav-tabs">
                <li><a href="/deliverer-profile">Thông tin Người giao hàng</a></li>
                <li><a href="/current-delivery">Đơn vận chuyển hiện tại</a></li>
                <li class="active"><a href="/deliverer-profile/delivery-list">Danh sách đơn vận chuyển</a></li>
            </ul>
            <br>

            <ul class="pagination" id = "order_pagination" style = "display:flex;">
                {% for i in page_range %}
                <li {% if i == 1 %}class="active"{% endif %} onclick = "orderListRefresh({{i}})"><a href = "/current-store/product-list/{{i}}">{{i}}</a></li>
                {% endfor %}
            </ul>

            <table class = "table table-hover" id ="order_table">
                <thead>
                    <tr>
                        <th>Thời điểm khởi tạo</th>
                        <th>Thời điểm nhận hàng</th>
                        <th>Phương thức thanh toán</th>
                        <th>Tình trạng đơn hàng</th>
                        <th>Tình trạng vận chuyển</th>
                        <th>Tình trạng thanh toán</th>
                        <th>Tổng tiền</th>
                        <th>Khách hàng</th>
                        <th>Tổng quảng đường vận chuyển</th>
                        <th>Hành động</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                    </tr>
                </tbody>
            </table>
            {% load static %}
            <script src = "{% static 'js/deliverer-order-list.js' %}"></script>
        {% else %}
            <meta http-equiv="refresh" content="1; url='/login'" />
            <div>
                <h3>You are not logged in now, so you will be directed to Login Page</h3>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/Site/Login.html
{% extends 'Site/index.html' %}
{% block content %}
    <div class = "container-fluid">
        <div class = "row">
            {% if not user.is_authenticated %}
            <div class = "col-md-4 p-4 text-center login-form">
                <form method = "POST">
                    {% csrf_token %}
                    <h3>Đăng nhập</h3>
                    <div class = "form-group">
                        <input type = "text" name = "username" placeholder = "Tài khoản">
                    </div>
                    <div class = "form-group">
                        <input type = "password" name = "password" placeholder = "Mật khẩu">
                    </div>
                        <small><a href="/register">Chưa có tài khoản? Đăng ký tại đây</a></small>
                    <div>
                        {% for msg in messages %}
                        <small style="color:red">{{msg}}</small>
                        {% endfor %}
                    </div>
                    <button type = "submit" class = "btn btn-primary">Đăng nhập</button>
                </form>
            </div>
            {% else %}
            {% if user.profile.is_deliverer %}
                <meta http-equiv="refresh" content="1; url='/deliverer-profile'" />
            {% elif user.profile.is_store_owner %}
                <meta http-equiv="refresh" content="1; url='/current-store'" />
            {% else %}
                <meta http-equiv="refresh" content="1; url='/'" />
            {% endif %}
            <div class = "col-md-6 p-4 text-center">
                <h3>You are logging in now. You will be directed to Homepage</h3>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/Site/Logout.html
{% extends 'Site/index.html' %}
{% block content %}
    <div class = "container-fluid">
        <div class = "row">
            {% if user.is_authenticated %}
            <div class = "col-md-6 p-4 text-center form-default">
                <form method = "POST">
                    {% csrf_token %}
                    <div class="modal-content">
                        <div class="modal-header">
                            <label>Đăng xuất</label>
                        </div>
                        <div class = "modal-body">
                            <h4>Bạn có chắc chắn muốn đăng xuất</h4>
                            <button type = "submit" class = "btn btn-default">Có</button>
                            <a href ="/">
                                <button type = "button" class = "btn btn-default">Không</button>
                            </a>
                        </div>
                    </div>

                </form>
            </div>
            {% else %}
            <meta http-equiv="refresh" content="1; url='/'" />
            <div class = "col-md-6 p-4 text-center">
                <h3>You are not logging in now. You will be directed to Homepage</h3>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/Site/ProductCreate.html
{% extends 'Site/index.html' %}
{% block content %}
<div class = "container-fluid">
        {% if user.is_authenticated %}
            {% if user.store %}
            <br>
            <button onclick = "window.location.replace('/current-store/product-list/1')" class = "btn">Trở lại</button>
            <hr>
            <ul class="col-md-2 nav nav-pills nav-stacked">
                <li class="active"><a data-toggle = "tab" href="#profile">Thông tin</a></li>
            </ul>
            <div class = "col-md-8 tab-content">
                <div class = "tab-pane fade in active" id = "profile">
                    <h2>Tạo món</h2>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h3>Hình ảnh</h3>
                        <input type = "hidden" name = "form_tag" value = "create_product" readonly>
                        <div class = "form-group">
                            <img id = "store_avatar" src = "">
                        </div>

                        <div>
                            <input type="file" name="image" id = "image_upload" accept="image/*" id="id_avatar">
                        </div>
                        <script>
                            $("#image_upload").change(function() {
                                input = this;
                                if (input.files && input.files[0]) {
                                    var reader = new FileReader();
                                    reader.onload = function(e) {
                                      $("#store_avatar").attr('src', e.target.result);
                                      $("#store_avatar").attr("style", "width:30vw; height:18.54vw;");
                                    }
                                    reader.readAsDataURL(input.files[0]);
                                }
                            });
                        </script>
                        {% if error == "avatar" %}
                        {% for msg in messages %}
                            <small style="color:red">{{msg}}</small>
                            <br>
                        {% endfor %}
                        {% endif %}
                            <h3>Thông tin cơ bản</h3>

                            <div class = "form-group">
                                <label>Tên<br></label>
                                <input type="text" name = "name" value = "">
                            </div>
                            <div class = "form-group">
                                <label>Giá(VND)<br></label>
                                <input type="number" name = "price" min = "0" step="0.01" value="" />
                            </div>
                            <div class = "form-group">
                                <label>Loại món:<br></label>
                                <select name = "category_id">
                                    {% for category in categories%}
                                    <option value = "{{category.id}}">{{category.name}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class = "form-group">
                                <label>Mô tả</label>
                                <br>
                                <textarea name = "description" style = "width:500px; height:250px"></textarea>
                            </div>
                            {% if error == "store" %}
                            {% for msg in messages %}
                                <small style="color:red">{{msg}}</small>
                                <br>
                            {% endfor %}
                            {% endif %}
                            <button type="submit" class="btn btn-primary" onClick="window.location.replace('/current-store/product-list/1')">Xác nhận</button>

                        </form>
                </div>
            </div>
            {% else %}
            <meta http-equiv="refresh" content="1; url='/'" />
            <div>
                <h3>Bạn không phải chủ cửa hàng, không thể thực hiện chức năng này</h3>
            </div>
            {% endif %}
        {% else %}
            <meta http-equiv="refresh" content="1; url='/login'" />
            <div>
                <h3>You are not logged in now, so you will be directed to Login Page</h3>
            </div>
        {% endif %}
</div>
{% endblock %}

templates/Site/ProductList.html
{% extends 'Site/index.html' %}

{% block content %}

    <div class = "container-fluid">
        <ul class="pagination" style = "display:flex;">
            {% for i in page_range %}
            <li {% if page.number == i %}class="active"{% endif %}><a href = "/product-list{% if search_keyword %}/search-keyword/{{search_keyword}}{% endif %}/{{i}}">{{i}}</a></li>
            {% endfor %}
        </ul>
        <hr>
        {% if search_keyword %}
        <h4>Kết quả tìm kiếm cho {{search_keyword}} ({{search_count}} kết quả)</h4>
        {% endif %}
        <div class = "row">


            <div class = "col-md-12">
                <div class = "row">
                {% for p in page.object_list %}


                    <div class = "col-md-2 product-card" style="margin:50px;">
                        <div style = "border-style:solid; border-width: thin; width: 202px;">
                            <img class = 'product-image' src="{{ p.image.url }}">
                        </div>
                        <div style = "border-style:solid; border-width: thin; width: 202px;">
                            <a href = "/product/{{ p.slug }}"><h4 style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;">{{ p.name }}</h4></a>
                        </div>
                        <div style = "border-style:solid; border-width: thin; width: 202px;">
                            <input id="rating_product_{{forloop.counter0}}" type="text" name = "rating" value = "{% if p.average_rating.rating__avg %}{{p.average_rating.rating__avg}}{% else %}0{% endif %}">
                            <script>
                                $("#rating_product_{{forloop.counter0}}").rating({min:0, max:5, step:0.5,
                                                                         size:'sm',starCaptions:(val)=>{return `${val} ({% if p.average_rating.author__count %}{{p.average_rating.author__count}}{% else %}0{% endif %} lượt đánh giá)`},
                                                                         displayOnly:true});
                            </script>
                        </div>
                        <div style = "border-style:solid; border-width: thin; width: 202px;">
                            <h5>{{ p.store.name }}</h5>
                            <h5 style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;">{{p.store.location.address}}</h5>
                            {% if p.distance %}
                                <h5>{{ p.distance }}km</h5>
                            {% endif %}
                            {% if p.store.is_open %}
                                <h5 style="color:green">Mở cửa</h5>
                            {% endif %}
                            <h5>{{ p.price }}</h5>
                        </div>
                    </div>


                {% endfor %}
                </div>
            </div>
            {% if user.profile.current_order and false %}
            <div class = "col current-order-form" style = "width: 32vw">
                {% if current_order %}
                    <form method = "POST">
                        {% csrf_token %}
                        <h2>Đơn hàng hiện tại</h2>
                        <h4>Giỏ hàng({{current_order.total_quantity}}):</h4>
                        <table class = "table table-hover" style = "width:8vw;">
                            <thead>
                                <tr>
                                    <th>Tên</th>
                                    <th>Hình ảnh</th>
                                    <th>Đơn giá</th>
                                    <th>Số Lượng</th>
                                    <th>Tổng</th>
                                </tr>
                            </thead>
                            <tbody>

                            {% for order_product in current_order.order_products.all %}
                                <tr>

                                    <td>
                                        <a href = "/product/{{order_product.product.slug}}"><h5>{{order_product.product.name}}</h5></a>
                                    </td>
                                    <td>
                                        <img class = "order-product-image" src = "{{order_product.product.image.url}}">
                                    </td>
                                    <td>{{order_product.price}}</td>
                                    <td>{{order_product.quantity}}</td>
                                    <td>{{order_product.total}}</td>
                                </tr>
                            {% endfor %}
                        </table>
                        <h4>Danh Sách Cửa Hàng:</h4>
                        <input type = "hidden" id="destination_lat" value = {{current_order.destination.lat}}>
                        <input type = "hidden" id="destination_lng" value = {{current_order.destination.lng}}>
                        <input type = "hidden" id="destination_address" value = "{{current_order.destination.address}}">
                        {% if store_list %}
                            <input type = "hidden" id="num_of_store" value = "{{store_list|length}}">
                            {% for i in store_list %}
                                <label id="store_{{ forloop.counter0 }}_name">{{i.name}}</label>
                                <input type = "hidden" id="store_{{ forloop.counter0 }}_lat" value = {{i.location.lat}}>
                                <input type = "hidden" id="store_{{ forloop.counter0 }}_lng" value = {{i.location.lng}}>
                                <input type = "hidden" id="store_{{ forloop.counter0 }}_address" value = "{{i.location.address}}">
                            {% endfor %}
                        {% endif %}
                        <h4>Bản đồ:</h4>
                        <div id = "map" style = "width:350px; height:216px;"></div>
                        <h4><a href="/current-order">Chỉnh sửa Thông tin đơn hàng</a></h4>
                    </form>
                    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />
                    <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>
                    <script src="https://unpkg.com/leaflet-ant-path@1.3.0/dist/leaflet-ant-path.js" type="text/javascript"></script>


                    <script src="https://unpkg.com/esri-leaflet@3.0.10/dist/esri-leaflet.js"></script>
                    <script src="https://unpkg.com/esri-leaflet-vector@4.0.1/dist/esri-leaflet-vector.js"></script>

                    <script src="https://unpkg.com/esri-leaflet-geocoder@3.1.4/dist/esri-leaflet-geocoder.js"></script>

                    <script src="https://unpkg.com/@esri/arcgis-rest-request@4.0.0/dist/bundled/request.umd.js"></script>
                    <script src="https://unpkg.com/@esri/arcgis-rest-routing@4.0.0/dist/bundled/routing.umd.js"></script>
                    {% load static %}
                    <script src = "{% static 'js/product-location-1.js' %}"></script>
                {% else %}
                    <form method = "POST">
                        {% csrf_token %}
                        <input type="hidden" name="form_tag" value = "create_order" readonly>
                        <button class = "btn" style = "display: flex; justify-content: space-between;">Tạo Đơn Hàng Mới</button>
                    </form>
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/Site/RoutingTest.html
{% extends 'Site/index.html' %}
{% block content %}
 <div id="map" style = "height: 500px; width:800px;"></div>
 <div>
   <input type = "text" id="lat">
   <input type = "text" id="lng">
 </div>
 <div>
   <label id="address"></label>
 </div>
 <div>
   <select id="choices">
   </select>
 </div>
 <div>
   <button class="btn btn-primary" id = "route-button">Route</button>
 </div>
<div>
    <label>Quảng đường cần dich chuyển:<label id = "direction"></label></label>
</div>
 <div>
   <label id="directions"></label>
 </div>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />
<script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>

<script src="https://unpkg.com/esri-leaflet@3.0.10/dist/esri-leaflet.js"></script>
<script src="https://unpkg.com/esri-leaflet-vector@4.0.1/dist/esri-leaflet-vector.js"></script>

<script src="https://unpkg.com/esri-leaflet-geocoder@3.1.4/dist/esri-leaflet-geocoder.js"></script>

<script src="https://unpkg.com/@esri/arcgis-rest-request@4.0.0/dist/bundled/request.umd.js"></script>
<script src="https://unpkg.com/@esri/arcgis-rest-routing@4.0.0/dist/bundled/routing.umd.js"></script>
 {% load static %}
 <script src = "{% static 'js/routing-test.js' %}"></script>
{% endblock %}